curl 'https://epassport.meituan.com/api/account/login?service=hotel&bg_source=4&loginContinue=https:%2F%2Febooking.meituan.com%2Fgw%2Faccount%2Fbiz%2Fsettoken%3Fredirect_uri%3Dhttps%253A%252F%252Febooking.meituan.com%252Febk%252Flogin%252Fsettoken.html&loginType=account' \
  -H 'Accept: application/json' \
  -H 'Accept-Language: zh,en;q=0.9,zh-CN;q=0.8,sq;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Cookie: test' \
  -H 'Origin: https://epassport.meituan.com' \
  -H 'Referer: https://epassport.meituan.com/account/unitivelogin?service=hotel&loginsource=14&noSignup=true&bg_source=4&loginurl=https%3A%2F%2Febooking.meituan.com%2Febk%2Flogin%2Flogin.html&continue=https%3A%2F%2Febooking.meituan.com%2Fgw%2Faccount%2Fbiz%2Fsettoken%3Fredirect_uri%3Dhttps%253A%252F%252Febooking.meituan.com%252Febk%252Flogin%252Fsettoken.html' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36' \
  -H 'dnt: 1' \
  -H 'sec-ch-ua: "Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-gpc: 1' \
  -H 'x-requested-with: XMLHttpRequest' \
  --data-raw '{"login":"123456","part_key":"","password":"123456","error":"需要滑块验证","success":"","isFetching":false,"loginType":"account","verifyRequestCode":"","verifyResponseCode":"","captchaCode":"","verifyType":3,"captchaToken":"","rohrToken":"eJyVU39v2jAQ/S6W4B8scH44JEhoCk3ZWgotK+3YJlSFYIKXEEe2AxVVv/suATo2rWorWeend3fPlxf7CcmLBeo8oWUaxqhjEEJs6xmjDZOog4wmaToII60g5bSpS9uW47kuwSg64ahBLMfBaC7vA9T5aXgmwR5xZiXzFYg9YxCXzPAh69IZNm1YZdEF1KCV1rnqtFosD5XKhdTNNeO6CLNmJNatMIpEkelWkXHNNywVMc8+KSY3PGLdldAsrVecEoUExrDrmbjlcVbkXS0LVp/HD4eUvS8sZNqtjqxZfs3sw2JzIRKexafnVnQCseo57s2VXqf1SGQadNj7ZOIthMNXAJrzHUTFtBYJy2pWX7IFlyzSD4XkNSvYa5q0VKWlLn1NmR5GpC9D0j/C1aTwAxHYvJ6UNnumA667wP0ftf9C3vsQJR9Gxj/I/QAyK+S9iazXkEXeRHZpWVJaBnt4ah3u3U0m1yOoNIjnYtvEftnVtjFc7WMSmvSxeQgvCSoUXEdA7HLb396fD+Izf9wbnbWZH1g3DS4TZ6x0Hu/i21EvbzS8xdWwHySDHl2q9GY63LnkyhwPN8G4oc/lavdt+ktL+n2gHj8vJ5fTH18acZ9e9zIfPf8Gq80Kvw=="}' \
  --compressed
